spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/rentacar}
    username: ${DATABASE_USERNAME:rentacar}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    locations: classpath:db/migration
    schemas: public

logging:
  level:
    com.nextstep.rentacar: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:dev-secret-key-256-bits-long-for-hmac-sha256-algorithm-development}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours

# CORS for development with frontend
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:8080}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  allow-credentials: true
